// vue/vuelog/src/components/Header.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Vuelog</a>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" aria-current="page" href="/">Home</a>
          <a class="nav-link" href="/list">Posts</a>
          <a class="nav-link" href="#">Pricing</a>
          <a
            class="nav-link disabled"
            href="#"
            tabindex="-1"
            aria-disabled="true"
            >Disabled</a
          >
        </div>
      </div>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Header'
};
</script>

<style></style>

// src/components/Header.jsx
import { Link } from 'react-router-dom';

function Header() {
  return (
    <nav className='navbar navbar-expand-sm bg-dark navbar-dark'>
      <div className='container-fluid'>
        <Link
          className='navbar-brand'
          to='/'>
          CRUD
        </Link>
        <button
          className='navbar-toggler'
          type='button'
          data-bs-toggle='collapse'
          data-bs-target='#collapsibleNavbar'>
          <span className='navbar-toggler-icon'></span>
        </button>
        <div
          className='collapse navbar-collapse'
          id='collapsibleNavbar'>
          <ul className='navbar-nav'>
            <li className='nav-item'>
              <Link
                className='nav-link'
                to='/create'>
                Create
              </Link>
            </li>
            <li className='nav-item'>
              <Link
                className='nav-link'
                to='/read'>
                Read
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  );
}

export default Header;
